apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ipfs-deployment
spec:
  replicas: 2 
  template: 
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
      - name: ipfs
        image: zjudistributeai/ipfs:v0.2
        ports:
        - containerPort: 4001
        - containerPort: 5001
        - containerPort: 8080
        - containerPort: 8081
      #   volumeMounts:
      #   - mountPath: /data/ipfs
      #     name: ipfs-data
      #   - mountPath: /export
      #     name: ipfs-staging
      # volumes:
      # - name: ipfs-data
      #   hostPath:
      #     path: /home/hyf/ipfs/data
      # - name: ipfs-staging
      #   hostPath:
      #     path: /home/hyf/ipfs/staging
       

