kind: Service
apiVersion: v1
metadata:
  name: ipfs-service
spec:
  type: NodePort
  selector:
    app: ipfs
  ports:
    - protocol: TCP
      name: webui
      port: 5001
      targetPort: 5001
      nodePort: 30001
    - protocol: TCP
      name: ipfshttp
      port: 8080
      targetPort: 8080
      nodePort: 30002